version: '3'

services:

  client:
    container_name: marketing_client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
    ports:
      - 3005:3000
    depends_on:
      - server

  server:
    container_name: marketing_server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    working_dir: /var/www/server
    volumes:
      - ./server:/var/www/server
    expose:
      - 5000
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always  
  
  db:
    container_name: marketing_db
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    expose:
      - 5432
    restart: always
  
  pgadmin:
    container_name: marketing-pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pg-admin-data:/var/lib/pgadmin    
    expose:
      - '80'
    ports:
      - '8080:80'
    restart: always
    